### ISSUE TITLE
生成的码流文件，怎么比图片本身还要大

### ISSUE THREAD

**Issue by jiafengshen** [ZZ022/ArIB-BPS#1]
生成的码流文件，怎么比图片本身还要大

**Comment by ZZ022** [comment]
请问是哪张图片

**Comment by jiafengshen** [comment]
找了张数字图片，用了cifar10的模型，输入的jpg大小是300多看kb，compress.py encode后的output有1000多kb

**Comment by ZZ022** [comment]
jpg是一个有损压缩的格式，压缩率本来就很大，但是会带来损失，无损这边应该采用png类似的格式的图片

**Comment by jiafengshen** [comment]
那cifar10的模型去压 域差的比较大的图片，比如人脸，会有效吗

**Comment by ZZ022** [comment]
我没有系统的测试过，刚刚测试了FFHQ256x256的00000.png，png格式的大小为102KB，cifar模型压出来图像76KB，imagenet模型压缩出来67KB

**Comment by jiafengshen** [comment]
你这套方案，可以用来压bayer数据吗，12bit，16bit的

**Comment by jiafengshen** [comment]
你对数据没有做归一化吗

**Comment by ZZ022** [comment]
目前的模型只支持8bit图片
