### ISSUE TITLE
作者的方法是否是无损压缩

### ISSUE THREAD

**Issue by Accept111** [ZZ022/ArIB-BPS#2]
作者您好，我跑了compress.py生成了一张压缩后重构的图片，我与原始图片进行逐像素对比，发现具有很多的像素差异，我想问一下这是无损压缩嘛？我也跑了测试代码和看了论文发下没有psnr或者ssim等相关指标，请问作者是否做了相关指标的实验。

**Comment by ZZ022** [comment]
我在测试集上的图片重建图像都是严格无损的。请问能否提供实验图像让我验证一下。

**Comment by Accept111** [comment]
![dog](https://github.com/user-attachments/assets/2a4066e3-31b4-4cda-9bbe-0a8ab58cf33f)
我是随便找了一张狗的图片，必须要是测试机上的图片才能做到无损嘛

**Comment by ZZ022** [comment]
我这边是完全无损的。请问最终输出的重建格式是png吗，如果是jpg的话就会导致有损，因为jpg是个有损压缩的格式。

**Comment by Accept111** [comment]
我这是jpg的，我再试一下png的。我还有个问题，您这个整体的架构是基于VAE的嘛

**Comment by ZZ022** [comment]
是基于vae和自回归的，详细信息可以参考论文

**Comment by Accept111** [comment]
论文我大概看了一遍，我看在您的实验部分做了BPD的对比，请问有没有像psnr和ssim相关的指标呢

**Comment by ZZ022** [comment]
由于所有的图片都是无损的，因此没有测量这两个指标。在测试代码中有一个指标是测试重建图像和原始图像是否完全相等的，在所有测试图片上均是完全想等。

**Comment by Accept111** [comment]
还有个问题就是划分平面的索引s是怎么得到的，是超参数还是别的？

**Comment by ZZ022** [comment]
这是一个超参数

**Comment by Accept111** [comment]
好的，感谢作者的回答
